name: enter_tainer
description: "Entertainer project."

publish_to: 'none'

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  neuss_utils:
    git:
      url: https://github.com/abuzeit/neuss_utils.git
      ref: ^1.0.9

  get: ^4.7.2
  get_storage: ^2.1.1

  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  firebase_analytics: ^11.5.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.7
  flutter_datetime_picker_plus: ^2.2.0
  flutter_sliding_box: ^1.1.5
  flutter_story_presenter: ^1.0.6

  uuid: ^4.5.1
  story_view: ^0.16.6
  #  vibration: ^3.1.3
  #  awesome_notifications: ^0.7.4+1
  #  awesome_notifications_fcm: ^0.7.4+1
  fcm_config: ^3.6.5
  timezone: ^0.10.0
  video_player: ^2.10.0

  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flex_color_scheme: ^8.2.0
  flare_flutter: ^3.0.2
  pin_code_fields: ^8.0.1
  loading_indicator: ^3.1.1
  font_awesome_flutter: ^10.8.0
  flutter_animate: ^4.5.2
  im_stepper: ^1.0.1+1

  paged_vertical_calendar: ^1.1.9
  infinite_scroll_pagination: ^3.2.0
  ready_extensions: ^1.3.2
  dart_extensions: ^2.2.4
  date_only_field: ^0.0.14

  permission_handler: ^12.0.0+1
  connectivity_plus: ^6.1.4

  carousel_slider: ^5.1.1
  #Map
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  location: ^7.0.0
  latlong2: ^0.9.1
  google_maps_flutter: ^2.9.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  google_api_headers: ^4.2.0
  flutter_map: 7.0.2
  flutter_osm_plugin: ^1.2.0
  flutter_map_marker_popup: ^7.0.0
  flutter_map_location_marker: ^9.0.0
  location_picker_flutter_map: ^3.1.0

dependency_overrides:
  win32: ^5.14.0
  http: ^1.4.0
  web: ^1.1.0
  ffi: ^2.1.4
  intl: ^0.20.2
  flutter_hooks: ^0.21.2
  url_launcher: ^6.3.1

  device_info_plus: ^11.5.0
  permission_handler: ^12.0.0+1
  flutter_svg: ^2.2.0
  package_info_plus: ^8.3.0
  flutter_map: 7.0.2
  geolocator: ^13.0.1
  location_picker_flutter_map: ^3.1.0
  location: ^8.0.1
  file_selector_linux: ^0.9.3+2
  uuid: ^4.5.1
  js: ^0.7.2
  infinite_scroll_pagination: ^4.0.0
  flutter_lints: ^5.0.0
  file_picker: ^10.2.0
  share_plus: ^11.0.0
  sensors_plus: ^6.1.1
  vm_service: ^15.0.2
  #  win32_registry: ^2.1.0
  signature: ^6.3.0
  flutter_map_location_marker: ^9.1.1


  #  firebase_core: ^3.11.0
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.2.0
  form_builder_extra_fields: ^12.0.0
  dropdown_search: ^6.0.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: assets/images/app_icon.png

# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#FFFFFF"
  image: assets/images/app_icon.png
  #  image_dark: assets/images/ic_launcher.png

  android_12:
    icon_background_color: "#FFFFFF"
    image: assets/images/app_icon5.png

  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/json/
